--- #YAML:1.0
name:                Audio-XMMSClient
version:             0.03
abstract:            Interface to the xmms2 music player
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
